version: '3'
services:
  backend:
    build: ./linglong
    ports:
      - "8080:8080"   # 后端端口映射（与前端请求匹配）
    volumes:
      - ./linglong:/app
    command: go run main.go

  frontend:
    build: ./frontend
    ports:
      - "8001:80"     # 前端端口映射（与浏览器访问匹配）
    volumes:
      - ./frontend:/app
